name: Docker Image CI

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cedkim/papermc-docker:${{ steps.get_version.outputs.VERSION }}
    - name: Push the Docker image
      run: docker push cedkim/papermc-docker:${{ steps.get_version.outputs.VERSION }}
    
